### ISSUE TITLE
Update camera driver 1.2.1 can't connect to c1 camera

### ISSUE THREAD

**Issue by DavidTung0706** [tier4/tier4_automotive_hdr_camera#10]
Hi,  I'm using RQX-58G (JetPack 4.6) with ISX021-C1 ,
At that time, the driver version (0.9.0) was used, but when I used gscam to open the camera on ROS Melodic env, I encountered many times that some cameras did not publish any data, and no error message was reported. When I had this problem, I had to close the exception port and reopen it until it successfully started posting data.
so I  update driver to 1.2.1, 
Install and restart according to 1.2.1 document, but can't connect any camera
Are there any solution to fix this?
Thank you.
![IMG_0177](https://github.com/tier4/tier4_automotive_hdr_camera/assets/46273567/1b135b3c-0f6b-4e49-8282-d674f2354d10)

**Comment by yk-fujii** [comment]
Hi @DavidTung0706 
Could you paste the dmesg result?

**Comment by DavidTung0706** [comment]
![Screenshot from 2023-06-13 11-04-40](https://github.com/tier4/tier4_automotive_hdr_camera/assets/46273567/7fc47f02-ebcd-462e-b613-e1f14d9248cd)
![Screenshot from 2023-06-13 11-05-22](https://github.com/tier4/tier4_automotive_hdr_camera/assets/46273567/49bf6407-93ee-468a-89ac-f41573dc0108)

**Comment by DavidTung0706** [comment]
Hi @yk-fujii  Is there any solution to the above problem at present?

**Comment by DavidTung0706** [comment]
Is there any solution to the above problem at present?

**Comment by DavidTung0706** [comment]
Hi @yk-fujii  Is there any solution to the above problem at present?

**Comment by yk-fujii** [comment]
@DavidTung0706 
Did you run the command `sudo /opt/nvidia/jetson-io/config-by-hardware.py -n 2="TIERIV ISX021 GMSL2 Camera Device Tree Overlay"` ?
Looking at the log, it seems that the DTB has not been updated.


This procedure is documented in the quick start guide:
https://github.com/tier4/tier4_automotive_hdr_camera/releases/download/v1.2.1/TIER.IV.Automotive.HDR.Camera.C1.Quick.Start.Guide.RQX-58G._EN_v0.7.pdf

**Comment by yk-fujii** [comment]
The results of the analysis are shown here.
- There was no error in the driver installation procedure.
- The RQX-58G was purchased a long time ago, and the version of the FPGA on board (the one used by Trigger2) was out of date.
- The driver was failing to initialize because it was assumed that FPGA was supported.

Action
- A temporary version was issued that can be initialized even if the FPGA does not support it. (v1.2.10)
- Proposed to talk to ADLINK about FPGA updates.


TODO
- Incorporate the provisional version into the official version.
